config/routes.rb
ARLInventory::Application.routes.draw do
  resources :hand_reciepts

  match '/users', :to => 'users#index', :as => "all_users", :via => "get"
  resources :groups

  resources :brands

  resources :categories

  resource :dashboard, :only => [:show]

  resources :roles_users

  resources :roles

  resources :inventory_records

  resources :locations

  resources :inventory_statuses

  resources :inventories

  get "home/index"

  devise_for :users

  root :to => 'home#index'

  match '*path(.:format)', :to => 'application#routing_error'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
    if user.has_role? :admin
        can :manage, :all
    else
        can :read, :all
    end

  end
end

app/models/brand.rb
class Brand < ActiveRecord::Base
  attr_accessible :name
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :description, :name

  has_many :inventory_categorys
  has_many :inventories, :through => :inventory_categorys

  validates :name, :presence => true
  validates :description, :presence => true
  
end

app/models/group.rb
class Group < ActiveRecord::Base
  attr_accessible :description, :name
end

app/models/hand_reciept.rb
require 'securerandom'

class HandReciept < ActiveRecord::Base
  belongs_to :user
  attr_accessible :reciept, :user_id

# scope :registered,    Inventory.where("id IN (select inventory_id from inventory_records where inventory_records.inventory_id = inventories.id)")

	def self.unique_reciept
		SecureRandom.hex(13)
	end

end

app/models/inventory.rb
class Inventory < ActiveRecord::Base
  resourcify
	
  attr_accessible :barcode, :description, :name, :purchase_date, :stocknumber, :category_ids

  has_many :inventory_records
  has_many :locations, :through => :inventory_records

  has_many :inventory_categorys
  has_many :categories, :through => :inventory_categorys

  validates :barcode, :presence => true
  validates :description, :presence => true
  validates :name, :presence => true
  validates :purchase_date, :presence => true

  scope :unregistered, where("id NOT IN (select inventory_id from inventory_records where inventory_records.inventory_id = inventories.id)")
  
  scope :registered,    Inventory.where("id IN (select inventory_id from inventory_records where inventory_records.inventory_id = inventories.id)")
  scope :checkedin,     Inventory.where("id IN (select inventory_id from inventory_records where inventory_records.inventory_id = inventories.id and inventory_status_id=2)")
  scope :checkedout,    Inventory.where("id IN (select inventory_id from inventory_records where inventory_records.inventory_id = inventories.id and inventory_status_id=3)")
  scope :missing,       Inventory.where("id IN (select inventory_id from inventory_records where inventory_records.inventory_id = inventories.id and inventory_status_id=4)")
  scope :deaccessioned, Inventory.where("id IN (select inventory_id from inventory_records where inventory_records.inventory_id = inventories.id and inventory_status_id=5)")

  # override the default "per_page" for kaminari pagination
  paginates_per 10

  # params[:category_ids].map{|cid| Category.find cid}
  def category_ids=(params)
      self.categories =[]
      params.each do |id|
        unless id.to_s.empty?
          category = Category.find(id)
          categories << category
        end
        save
      end
  end



end

app/models/inventory_category.rb
class InventoryCategory < ActiveRecord::Base
  belongs_to :inventory
  belongs_to :category
  # attr_accessible :title, :body
end

app/models/inventory_record.rb
class InventoryRecord < ActiveRecord::Base
  resourcify

  belongs_to :user #, :inverse_of => :inventory_records
  belongs_to :inventory #, :inverse_of => :inventory_records
  belongs_to :inventory_status #, :inverse_of => :inventory_records
  belongs_to :location #, :inverse_of => :inventory_records
  
  attr_accessible :user_id, :inventory_id, :inventory_status_id, :location_id, :inventory_ids
  # , :latitude, :longitude


  
  validates :user_id, :presence => true
  validates :inventory_id, :presence => true
  validates :inventory_status_id , :presence => true
  validates :location_id, :presence => true
  # validates :latitude, :presence => true
  # validates :longitude, :presence => true


  def self.search(search)
    if search
      find(:all, 
           :joins => [:user, :inventory, :location],
           :conditions =>
           ['users.display_name LIKE ? OR inventories.name LIKE ? OR locations.name LIKE ?',
            "%#{search}%","%#{search}%","%#{search}%"])
    else
      find(:all)
    end
  end
end

app/models/inventory_status.rb
class InventoryStatus < ActiveRecord::Base
  resourcify
  
  attr_accessible :name

  validates :name, :presence => true

  has_many :inventory_records
end

app/models/location.rb
class Location < ActiveRecord::Base

  resourcify

  

  attr_accessible :latitude, :longitude, :name, :address

acts_as_gmappable :latitude => 'latitude', :longitude => 'longitude', :process_geocoding => :geocode?,

:address => 'address', :normalized_address => 'address',:msg => "Sorry, not even Google could figure out where that is"

  # geocoded_by :address
  # after_validation :geocode

  validates :name, :presence => true
  validates :address, :presence => true
  # validates :latitude, :presence => true
  # validates :longitude, :presence => true

  def geocode?
  	(!address.blank? && (latitude.blank? || longitude.blank?)) || address_changed?
  end

  def gmaps4rails_address
	address  		
  end

  def gmaps4rails_infowindow
  	"<h4>#{name}</h4>" << "<h4>#{address}</h4>"
  end

end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :display_name
  # attr_accessible :title, :body
	
	validates :email, :presence => true
	validates :password, :presence => true
	validates :password_confirmation, :presence => true
	validates :display_name, :presence => true

  has_many :inventory_records
  has_many :inventories, :through => :inventory_records				
  has_one  :hand_reciept
# override the default "per_page" for kaminari pagination
  paginates_per 5

	def avatar
		Gravatar.new(self.email).image_url
	end

  def admin?
    has_role?(:admin)
  end

  def user?
    has_role?(:user) || admin?
  end

end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper

	def title(page_title, show_title=true)
	  content_for(:title){h(page_title.to_s)}
	  @show_title = show_title
	end

	def show_title?
	  @show_title
	end

end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/shared/_navigation.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">	
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="brand" href="/">Inventory System</a>
			<div class="nav-collapse collapse">
		        
		        <ul class="nav">
		          	<% if current_user %>
		          	<li><a href="/dashboard/">Dashboard</a></li>
		          	<% end %>
		        	<% if current_user && current_user.admin? %>
			          <li class="dropdown">
			              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Management <b class="caret"></b></a>
			              <ul class="dropdown-menu">
					          <li><a href="<%= "#{inventories_path}" %>">Inventory</a></li>
					          <li><a href="<%= "#{inventory_records_path}" %>">Inventory Records</a></li>
					          <li><%= link_to "Hand Reciept", hand_reciepts_path %></li>
			                <li class="divider"></li>
			                <li class="nav-header">Admin</li>
			                <li><a href="<%= "#{inventory_statuses_path}" %>">Inventory Status</a></li>
					        <li><a href="<%= "#{locations_path}" %>">Locations</a></li>
					        <li><a href="<%= "#{categories_path}" %>">Categories</a></li>
					        <li><a href="<%= "#{brands_path}" %>">Brands</a></li>
					        <li><a href="<%= "#{roles_path}" %>">Roles</a></li>
					        <li><a href="<%= "#{all_users_path}" %>">Users</a></li>
			              </ul>
			          </li>
		        	<% end %>
		        </ul>
		        
		        <ul class="nav pull-right">
		          <% if current_user %>  
		              <li class="dropdown">
		                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Logged in as <img src="<%= current_user.avatar%>" class="avatar"></img> <%= current_user.display_name %><b class="caret"></b></a>
		                <ul class="dropdown-menu">
		                  <li><%= link_to 'My Inventories', inventory_records_path(:user_id =>current_user) %></li>
		                  <li><%= link_to 'Sign out', destroy_user_session_url(), :method => :delete %></li>  
		                  <li><%= link_to "Profile", edit_user_registration_path(current_user) %></li>
		                </ul>
		              </li>
		          <% else %>
		              <li><%= link_to 'Sign up', new_user_registration_url() %></li>
		              <li><%= link_to 'Sign in', new_user_session_url() %></li>
		          <% end %>
		        </ul>
		        <% if current_user && current_user.admin? %>
		        <div class="nav pull-right">
		        	<%= form_tag inventory_records_path, :id=> "search-form", :class => "navbar-search pull-right", :method => :get do %>
		        	<%= text_field_tag :search, nil, :class => "search-query", :placeholder => "Search..." %>
		        	<% end %>
		        </div>
		        <% end %>  
		        <!-- 
		 			<form class="navbar-form pull-right">
		              <input class="span2" type="text" placeholder="Email">
		              <input class="span2" type="password" placeholder="Password">
		              <button type="submit" class="btn">Sign in</button>
		            </form>
		         -->
	      </div><!--/.nav-collapse -->
		</div>
	</div>
</div>